name: tekartik_google_jsapi_picker
version: 0.2.2+1
description: file picker api
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  tekartik_google_jsapi:
    git:
      url: https://github.com/alextekartik/google-jsapi.dart
      ref: dart3a
    version: '>=0.2.0'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
  http:
dev_dependencies:
  yaml:
  dev_build:
  tekartik_bootstrap:
    git:
      url: https://github.com/tekartik/bootstrap.dart
      ref: dart3a
    version: '>=0.3.0'
  build_runner:
  build_test:
  build_web_compilers:
  test: any
  process_run: '>=1.0.0'
  googleapis_auth: '>=1.6.0'
