name: tekartik_google_jsapi_picker
version: 0.2.2+1
description: file picker api
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  tekartik_google_jsapi:
    git:
      url: https://github.com/alextekartik/google-jsapi.dart
      ref: dart3a
    version: '>=0.2.0'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
  http:
dev_dependencies:
  yaml: ">=3.1.2"
  dev_build: ">=1.1.0+2"
  tekartik_bootstrap:
    git:
      url: https://github.com/tekartik/bootstrap.dart
      ref: dart3a
    version: '>=0.3.0'
  build_runner: ">=2.4.13"
  build_test:
  build_web_compilers: ">=4.0.11"
  test: ">=1.24.0"
  process_run: ">=1.2.1+1"
  googleapis_auth: '>=1.6.0'
  tekartik_js_utils:
    git:
      url: https://github.com/tekartik/js_utils.dart
      ref: dart3a
      path: js_utils
